mapbox/turf-swift

- Turf.xcodeproj/project.pbxproj
Removes a stray reference to a plist file that doesn't exist.
@1ec5 👀
> Remove stray ref

- Turf/CoreLocation.swift
Make `toRadians` and `toDegrees` public.
@1ec5 👀
> Change access level on conversion methods

- Turf.podspec
Deploying backwards to Mac OS X 10.0 is probably not a great use of our time.
/cc @friedbunny
> Yosemite, not Cheetah

- README.md
Rewrote the “Installation” section of the readme, adding sections for Carthage and SPM. Also, the name of the pod is `Turf`, not `Turf-swift`.
/cc @frederoni @captainbarbosa
> Rewrite installation instructions

- .travis.yml
Closes #35 
Compiles turf-swift on Ubuntu trusty using Swift 4.0.3
Unfortunately, no tests are running yet because [SPM doesn't support resources](https://bugs.swift.org/browse/SR-2866).
@1ec5 👀
> Set up continuous integration on Linux

- Sources/Turf/CoreLocation.swift
Removes this warning:
/cc @mapbox/navigation-ios @captainbarbosa
> Remove swift 4.1 warning

- Turf.podspec
If this is left wide open, all and any file type get copied over when using cocoapods. If used in conjunction with xcode 10, it fails to compile and complains it's copied twice.
Should this also include .h files?
/cc @1ec5 @frederoni
> Add support for xcode 10, only import swift files

- README.md
- Sources/Turf/Codable.swift
- Sources/Turf/FeatureCollection.swift
- Sources/Turf/GeoJSON.swift
- Sources/Turf/LineString.swift
- Sources/Turf/MultiLineString.swift
- Sources/Turf/MultiPoint.swift
- Sources/Turf/MultiPolygon.swift
- Sources/Turf/Point.swift
- Sources/Turf/Polygon.swift
- Tests/TurfTests/FeatureCollectionTests.swift
- Tests/TurfTests/MultiPointTests.swift
- Tests/TurfTests/MultiPolygonTests.swift
- Tests/TurfTests/PointTests.swift
- Tests/TurfTests/PolygonTests.swift
- Tests/TurfTests/TurfTests.swift
Top level type `Feature` and `FeatureCollection` was missing from the feature objects resulting in malformed GeoJSON data. This change fixes that and also exposes public initializers for all geometries and features and cleans up unwanted IUO.
cc @1ec5 @jmkiley
> Encode GeoJSON feature type

- Turf.xcodeproj/project.pbxproj
Fixed the following error seen when building the Mac scheme in Xcode 10b3:
```
error: Multiple commands produce '/Users/mxn/Library/Developer/Xcode/DerivedData/Turf-dvjeqjrcvwliboawqsnbhzgudzba/Build/Products/Debug/Turf.framework/Versions/A/Resources/Info.plist':
1) Target 'TurfMac' (project 'Turf') has copy command from '/Users/mxn/hub/turf-swift/Tests/TurfTests/Info.plist' to '/Users/mxn/Library/Developer/Xcode/DerivedData/Turf-dvjeqjrcvwliboawqsnbhzgudzba/Build/Products/Debug/Turf.framework/Versions/A/Resources/Info.plist'
2) Target 'TurfMac' (project 'Turf') has process command with input '/Users/mxn/hub/turf-swift/Sources/Turf/Info.plist'
```
/cc @frederoni
> Remove redundant Info.plist copying from Mac target

- README.md
- Sources/Turf/BoundingBox.swift
- Sources/Turf/Polygon.swift
- Sources/Turf/Ring.swift
- Tests/TurfTests/PolygonTests.swift
- Turf.xcodeproj/project.pbxproj
Uses the identical algorithm as used in Turf.js.
https://github.com/Turfjs/turf/blob/e53677b0931da9e38bb947da448ee7404adc369d/packages/turf-boolean-point-in-polygon/index.ts
> Ported the turf-boolean-point-in-polygon function to Turf Swift.

- Sources/Turf/BoundingBox.swift
- Tests/TurfTests/BoundingBoxTests.swift
- Turf.xcodeproj/project.pbxproj
Rebased https://github.com/mapbox/turf-swift/pull/65
Not sure how I missed this, but the default values in the reduce func in the initializer causes a lot of problems for things not bounding around the lat lon of (0, 0).
Made BoundingBox.northWest and BoundingBox.southEast public and mutable.
> Fixed erroneous initializer in the previous commit

- Sources/Turf/LineString.swift
Supplemented `LineString.coordinateFromStart(distance:)` with an implementation that returns an `IndexedCoordinate`, making it easier for clients to stop assuming that a line string never doubles back on itself.
/cc @frederoni
> Indexed coordinate from start of line string

- Sources/Turf/LineString.swift
- Tests/TurfTests/LineStringTests.swift
Fixed an issue where `LineString.sliced(from:to:)` duplicated the last coordinate if `to` is omitted or equal to the end of the line string.
/cc @frederoni
> Fix redundant coordinate at end of line slice

- Turf.xcodeproj/project.pbxproj
`featurecollection-no-properties.geojson` was added to the iOS framework in #61 and distributed as part of the framework, but it's just a test fixture.
cc @1ec5
> Remove fixture from iOS framework

- README.md
- Sources/Turf/FeatureCollection.swift
- Sources/Turf/LineString.swift
- Sources/Turf/MultiLineString.swift
Added initializers based on the [polygon-to-line](https://github.com/Turfjs/turf/tree/b6cb691e0d23293ca0c881fe561f0e8a4536ad6a/packages/turf-polygon-to-line) package to convert from Ring to LineString, from Polygon to MultiLineString, and from MultiPolygon to a FeatureCollection containing a mixture of LineStringFeatures and MultiLineStringFeatures.
Fixes #81.
/cc @samfader @frederoni
> Add conversions between polygons and line strings

- Sources/Turf/BoundingBox.swift
- Sources/Turf/Codable.swift
- Sources/Turf/CoreLocation.swift
- Sources/Turf/Geometry.swift
Resolves #84 
Removed `CLLocationCoordinate` `Codable` conformance. 
Since there is no such thing as "Private protocol conformance" in Swift, I implemented `CLLocationCoordinate2DCodable` wrapper to handle encoding and decoding. This solution allows smooth en|decoding of `CLLocationCoordinate` inside `Turf`, and allows user to implement their own `Codable` conformance if they need to.
> CLLocationCoordinate Codable private conformance

- Sources/Turf/Codable.swift
- Sources/Turf/Feature.swift
- Sources/Turf/FeatureCollection.swift
- Sources/Turf/GeoJSON.swift
- Tests/TurfTests/FeatureCollectionTests.swift
- Tests/TurfTests/MultiPolygonTests.swift
Resolves #94 
* removed JSONType and AnyJSONType
* GeoJSON properties are now `[String; Any?]` type
* Implemented  encoding and decoding specializations for dictionaries and arrays with `Any?` type.
> JSON Representations refactor

- Sources/Turf/BoundingBox.swift
- Sources/Turf/Polygon.swift
- Sources/Turf/Ring.swift
- Tests/TurfTests/BoundingBoxTests.swift
- Tests/TurfTests/PolygonTests.swift
Fixes #88
-   **Fix `Polygon.contains` at boundary**
`Polygon.contains(_:ignoreBoundary:)` with `ignoreBoundary` set to `false` (the default), was returning `false` for a point at the boundary that coincides with the bounding box. This is because the optimization that first checks whether the point is contained by the polygon's bounding box, which uses `BoundingBox.contains(_:)`, did not consider a point at the boundary as being contained.
To address this, `BoundingBox.contains(_:)` is extended with a second argument `ignoreBoundary` defaulting to `true` for backwards compatibility.  The optimization in `Polygon.contains(_:ignoreBoundary:)` now forwards the `ignoreBoundary` argument, fixing the issue.
-   **Move containment optimization from `Polygon` to `Ring`** …
> Fix Polygon.contains

- README.md
- Sources/Turf/Feature.swift
- Sources/Turf/FeatureCollection.swift
- Sources/Turf/Geometries/GeometryCollection.swift
- Sources/Turf/Geometry.swift
- Tests/TurfTests/FeatureCollectionTests.swift
- Tests/TurfTests/GeoJSONTests.swift
- Tests/TurfTests/GeometryCollectionTests.swift
- Tests/TurfTests/LineStringTests.swift
- Tests/TurfTests/MultiLineStringTests.swift
- Tests/TurfTests/MultiPointTests.swift
- Tests/TurfTests/MultiPolygonTests.swift
- Tests/TurfTests/PointTests.swift
- Tests/TurfTests/PolygonTests.swift
This PR makes a couple changes to make the GeoJSON interface read better in Swift:
* Moved argument labels to GeoJSON struct initializers. It was misleading to label a geometry-typed associated value as `coordinates`. Labeling the `Geometry`-typed argument to `Feature`’s initializer means less confusion as we continue to add convenience initializers.
* Lowercased the first letter of each of `Geometry`’s cases, per Swift naming conventions. (GeoJSON always capitalizes these terms, but Swift lowercases capitalized terms at the beginning of case names anyways, like `.url` and `.mapbox`.)
For example:
```swift
// Before
Feature(.Point(coordinates: Point(coordinate)))
// After
Feature(geometry: .point(Point(coordinate)))
```
Some errors have been corrected in the example code in the readme. …
> Apply Swift naming conventions to GeoJSON initializers

- Sources/Turf/Geometries/GeometryCollection.swift
- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Geometries/MultiLineString.swift
- Sources/Turf/Geometries/MultiPoint.swift
- Sources/Turf/Geometries/MultiPolygon.swift
- Sources/Turf/Geometries/Point.swift
- Sources/Turf/Geometries/Polygon.swift
Resolves #103 
Made all Geometries struct's coordinates (or geometries for `GeometryCollection`) readwrite for convenience reasons.
> Geometries coordinates mutable

- Sources/Turf/Geometries/LineString.swift
- Tests/TurfTests/LineStringTests.swift
Fixes #78 
Fixed 'closesCoordinate' method to return correct indexed coordinate distance, measured from Line's first coordinate (as promised in the [doc](https://github.com/mapbox/turf-swift/blob/1114acd2e35512586d3917b1c5f12f4d74344fb7/Sources/Turf/LineString.swift#L92-L104)).
> IndexedCoordinate distance

- Sources/Turf/Geometries/Point.swift
~Changes the initializer for `Point` so that the argument label and parameter is `coordinate` instead of `coordinates` for grammatical consistency.~ This is part of the GeoJSON specification, so I've changed this PR to just clarify that in the docs.
> Document plurality of Point geometry

- README.md
- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Turf.swift
- Tests/TurfTests/TurfTests.swift
Removed the Turf struct, which conflicted with the Turf module name.
Fixes #110.
/cc @mapbox/navigation-ios @mapbox/maps-ios @frederoni
> Rename Turf.intersection(_:_:) to intersection(_:_:)

- Sources/Turf/CoreLocation.swift
Made `CLLocationCoordinate2D.latitude` and `longitude` public and added a public initializer in the Core Location compatibility shim for Linux, so that Linux clients can use this type that they have no choice but to use.
/ref https://github.com/mapbox/turf-swift/issues/119#issuecomment-722648354 raphaelmor/Polyline#69
/cc @Udumft @frederoni
> Make CLLocationCoordinate2D members public on Linux

- README.md
- Sources/Turf/BoundingBox.swift
- Sources/Turf/Codable.swift
- Sources/Turf/CoreLocation.swift
- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Geometries/MultiLineString.swift
- Sources/Turf/Geometries/MultiPoint.swift
- Sources/Turf/Geometries/MultiPolygon.swift
- Sources/Turf/Geometries/Point.swift
- Sources/Turf/Geometries/Polygon.swift
- Sources/Turf/Geometry.swift
- Sources/Turf/RadianCoordinate2D.swift
- Sources/Turf/Ring.swift
- Sources/Turf/Spline.swift
- Sources/Turf/Turf.swift
- Tests/TurfTests/BoundingBoxTests.swift
- Tests/TurfTests/GeoJSONTests.swift
- Tests/TurfTests/GeometryCollectionTests.swift
- Tests/TurfTests/LineStringTests.swift
- Tests/TurfTests/MultiLineStringTests.swift
- Tests/TurfTests/MultiPointTests.swift
- Tests/TurfTests/MultiPolygonTests.swift
- Tests/TurfTests/PointTests.swift
- Tests/TurfTests/PolygonTests.swift
- Tests/TurfTests/TurfTests.swift
Rewrote the Core Location compatibility shim for Linux to define non-CL-prefixed types regardless of platform. For example, cross-platform code uses `LocationCoordinate2D` instead of `CLLocationCoordinate2D`, but Apple-platform code can continue to use `CLLocationCoordinate2D`.
Along the way, this PR also renames `BoundingBox(_:_:)` to `BoundingBox(southWest:northEast:)` to avoid mistakes similar to #102 in client code.
Fixes #119.
/cc @mapbox/navigation-ios @macdrevx
> Rewrite Core Location shim for Linux

- README.md
- Sources/Turf/Geometries/Polygon.swift
- Tests/TurfTests/PolygonTests.swift
Added Polygon simplify.
The expected output numbers had to be altered with more precision from what you see [here](https://github.com/Turfjs/turf/blob/402716a29f6ae16bf3d0220e213e5380cc5a50c4/packages/turf-simplify/test/out/simple-polygon.geojson#L10-L13)
I noticed this was done with the `LineString` tests as well.
> Add Polygon simplify

- Sources/Turf/CoreLocation.swift
- Sources/Turf/RadianCoordinate2D.swift
- Tests/TurfTests/LocationCoordinate2DTests.swift
- Tests/TurfTests/RadianCoordinate2DTests.swift
- Turf.xcodeproj/project.pbxproj
Fixes #38.
New Measurement API is available from iOS 10 and allows to specify concrete units for all measurements.
Previously we expected a Double value in radians, however, it was possible for the user to pass Double value in degrees.
This PR ensures that the user will pass only values that are measured in radians.
> Use Measurement API instead of RadianDirection typealias

- .travis.yml
- scripts/install_swiftenv.sh
This PR copies the swiftenv installation script from https://swiftenv.fuller.li/en/latest/install.sh, since the script is stable and quite simple. It is unfortunately still necessary because the Travis image still has the Swift 4._x_ toolchain installed by default.
/cc @mapbox/navigation-ios
> Vendor swiftenv installation script

- Sources/Turf/Geometries/LineString.swift
Features in the LineString.swift file are all public except for the bezier function, which we need in our projet.
This PR fixes this.
> Make bezier feature on LineString public.

- README.md
- Sources/Turf/CoreLocation.swift
- Sources/Turf/Geometries/Polygon.swift
- Tests/TurfTests/PolygonTests.swift
This ports Turf's [`centerOfMass`](http://turfjs.org/docs/#centerOfMass) and [`centroid`](http://turfjs.org/docs/#centroid) to Swift, at least for the individual `Polygon` case. I've followed the same implementation and test cases as from the JS repo. 
Note: This could be extended to support the other geometries that Turf.js supports, though this should then also add support for convex hull calculations.
This addresses part of #145.
> Add Polygon centroid and center of mass

- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Geometries/Polygon.swift
- Tests/TurfTests/TurfTests.swift
Renamed `LineString.simplify(tolerance:highestQuality:)` and `Polygon.simplify(tolerance:highestQuality:)` to `LineString.simplified(tolerance:highestQuality:)` and `Polygon.simplified(tolerance:highestQuality:)`, respectively and vice versa. Mutating methods should be named in the imperative mood; nonmutating methods should be named with past participles.
/cc @macdrevx @nighthawk
> Swap names of simplify and simplified

- README.md
- Sources/Turf/CoreLocation.swift
- Sources/Turf/Feature.swift
- Sources/Turf/FeatureCollection.swift
- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Geometries/MultiLineString.swift
- Sources/Turf/Geometries/MultiPolygon.swift
- Sources/Turf/Geometries/Polygon.swift
- Sources/Turf/RadianCoordinate2D.swift
- Sources/Turf/Turf.swift
- docs/jazzy.yml
- scripts/document.sh
- scripts/update-version.sh
Added a script to generate an API reference docset using jazzy. The script and jazzy configuration are based on that of [MapboxDirections](https://github.com/mapbox/mapbox-directions-swift/blob/main/scripts/document.sh/), except for the Mapbox branding. It just uses the default jazzy theme, which comes with a handy search box. For now, the docset will be published to mapbox.github.io using GitHub Pages like some other small projects in this GitHub organization.
Documented the rest of the public symbols. Updated some documentation comments that had been referring to symbols removed in v1.0.0. Added inline cross-references to each ported initializer, method, and property to indicate the Turf.js package and method it was ported from. Linked the readme to [the Turf.js demonstration …
> Generate API reference documentation

- Sources/Turf/Feature.swift
- Sources/Turf/FeatureIdentifier.swift
- Sources/Turf/GeoJSON.swift
- Sources/Turf/Geometry.swift
- Sources/Turf/JSON.swift
- Tests/TurfTests/GeoJSONTests.swift
Added protocol-based initializers to `Geometry` and `GeoJSONObject` that accept each case’s associated value as an initializer argument. This makes the enumerations more consistent with the `JSONValue` and `FeatureIdentifier` enumerations and simplifies some common workflows.
JSONValue and FeatureIdentifier now conform to the `Hashable` protocol. These types are likely to be used as dictionary keys or set members, and it’s pretty easy to make them hashable.
Fixes #158.
/cc @mapbox/navigation-ios @mapbox/maps-ios
> Add conversions between enumerations and associated values

- README.md
- Sources/Turf/Geometries/LineString.swift
- Tests/TurfTests/LineStringTests.swift
To fix #156 , adding the method of `LineString.trimmed(from:to:) ` , to return a sliced `LineString` based on the starting distance and stop distance.
> Add method of LineString.trimmed(from:to:)

- README.md
- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Turf.swift
- Tests/TurfTests/LineStringTests.swift
- Tests/TurfTests/TurfTests.swift
Resolves #141 
PR adds zLinestring.intersection(with:)` method.
> Linestring.intersection method

- Sources/Turf/Codable.swift
- Sources/Turf/Feature.swift
- Sources/Turf/FeatureCollection.swift
- Sources/Turf/GeoJSON.swift
- Sources/Turf/Geometries/GeometryCollection.swift
- Sources/Turf/Geometries/LineString.swift
- Sources/Turf/Geometries/MultiLineString.swift
- Sources/Turf/Geometries/MultiPoint.swift
- Sources/Turf/Geometries/MultiPolygon.swift
- Sources/Turf/Geometries/Point.swift
- Sources/Turf/Geometries/Polygon.swift
- Sources/Turf/Ring.swift
- Tests/TurfTests/GeoJSONTests.swift
Any concrete GeoJSON object type can now store and round-trip foreign members back to JSON. For example, we now preserve properties such as `crs` (common in ArcGIS output) and `when` (part of the [GeoJSON-T](https://github.com/kgeographer/geojson-t/) extension). However, foreign members aren’t interpreted in any way, so if a nonstandard CRS is provided, this library’s various spatial functions will probably misinterpret the coordinates. This behavior is consistent with the GeoJSON specification, RFC&nbsp;7946.
Fixes #174.
/cc @Udumft @macdrevx @SiarheiFedartsou
> Round-trip GeoJSON foreign members

- Sources/Turf/JSON.swift
- Tests/TurfTests/JSONTests.swift
Previously, initializing `JSONValue` with `NSNumber` with value 0 or 1 would produce `JSONValue.boolean`. This change updates the behavior to only interpret `NSNumber` as boolean if its `objCType` is `'c'` and its value is 0 or 1.
> Only unbox NSNumbers 0, 1 to Bool for objCType 'c'

- Sources/Turf/Geometries/LineString.swift
So, I found the performance of the `LineString.trimmed(from:to:)` to be unusably slow and that it's caused by this distance calculation.
Calculating the distance between coordinates `i` and `i+1` can be done with a simple/cheap `distance(to:)`, but instead the `LineString.distance(from:to:)` is used, which kills performance because it allows `from`/`to` to not be on the line and has to calculate which line coordinate is closest using `closestCoordinate(to:)`, a O(n) operation, which leaves `trimmed(from:to:)` at a terrible O(n^2).
Please let me know if I'm missing anything.
> Improve performance of trimmed(from:,to:)

- Turf.xcodeproj/project.pbxproj
This PR changes the order of build phases but to the default. Otherwise, a complex projects cannot compile because of task planning issues.
> Reorder build phases to make Headers before build sources

- .travis.yml
- Package.swift
- Tests/LinuxMain.swift
- Tests/TurfTests/Fixture.swift
- Tests/TurfTests/GeoJSONTests.swift
- Tests/TurfTests/LineStringTests.swift
- Tests/TurfTests/TurfTests.swift
- Tests/TurfTests/WKTTests.swift
- Turf.xcodeproj/project.pbxproj
PR updates swift version used on Travis CI linux job which enables automatic test discovery on Linux platform. Unit tests and SPM target corrected with found errors. 
Had to update Linux distributive from `Trusty` to `Xenial` since Ubuntu 14.04 does not come with Swift 5.4 support, and minimal supported version is Ubuntu 16.04 (as found [here](https://www.swift.org/download/)) which is represented with `Xenial` dist on [Travis](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment).
> Enabling automatic test discovery on Linux

- .circleci/config.yml
- Package.swift
- README.md
- Turf.podspec
- Turf.xcodeproj/project.pbxproj
This PR supports visionOS target. 
It also bumps the **minimal xcode version to 14.1**. This is required to use `.custom("visionOS", versionString: "1.0")` in spm, which is supported starting from swift 5.6. However, I decided it's safe to bump the minimal swift version to 5.7, as Xcode 14.1 is the minimal supported version for AppStore distribution.
Also, added CI test runs on iOS and visionOS simulators.
> Support visionOS target

- scripts/document.sh
Fix github links in the Jazzy docs to point turf repo instead of directions-swift
> Fix github file prefix

- Sources/Turf/FeatureIdentifier.swift
- Sources/Turf/GeoJSON.swift
- Sources/Turf/Geometry.swift
- Sources/Turf/JSON.swift
- Tests/TurfTests/FeatureIdentifier.swift
- Tests/TurfTests/GeoJSONTests.swift
- Tests/TurfTests/GeometryTests.swift
- Tests/TurfTests/JSONTests.swift
This PR adds several extensions that allow enum value to be easily red and chained.
For example,
```swift
aFeature.geometry.point?.map(\.foo)
```
```swift
if let fooString = aFeature.properties.object?["foo"].string {
}
```
Doing the same with the `if let .case(foo) = bar` construction is usually cumbersome and doesn't support chaining.
> Add convenience accessors to enum values
